import '#/styles/globals.css';

import type { Metadata } from 'next';

import AnimatedCursor from '#/components/animatedCursor/AnimatedCursor';
import Header from '#/components/header';
import RotatingLogo from '#/components/rotatingLogo';
import { TailwindIndicator } from '#/components/tailwind-indicator';
import { Atyp, Suisse } from '#/lib/customFonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` text-dark  flex flex-col bg-[#e9c6dd] ${Suisse.variable} ${Atyp.variable}`}
      >
        <Header />
        <div className=" text-purple min-h-screen overflow-hidden md:px-8">
          {children}
        </div>
        <RotatingLogo />
        <TailwindIndicator />
        <AnimatedCursor />
        {/* <AnimatedCursor
          outerStyle={{
            border: '3px solid hsl(var(--drk))',
            backgroundColor: '#eed9e7',
          }}
          innerStyle={{
            backgroundColor: 'hsl(var(--drk))',
          }}
          clickables={[
            'a',
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            'label[for]',
            'select',
            'textarea',
            'button',
            '.link',
            {
              target: '.custom',
              options: {
                innerSize: 900,
                innerStyle: {
                  backgroundColor: 'hsl(var(--lgt))',
                },
                outerSize: 12,
                color: '255, 255, 255',
                outerAlpha: 0.3,
                innerScale: 0.7,
                outerScale: 5,
              },
            },
          ]}
        >
          Drag
        </AnimatedCursor> */}
      </body>
    </html>
  );
}
