import '#/styles/globals.css';

import type { Metadata } from 'next';

import Header from '#/components/header';
import RotatingLogo from '#/components/rotatingLogo';
import { TailwindIndicator } from '#/components/tailwind-indicator';
import { Atyp, Suisse } from '#/lib/customFonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` text-dark  flex flex-col bg-[#e9c6dd] ${Suisse.variable} ${Atyp.variable}`}
      >
        <Header />
        <div className=" text-purple min-h-screen overflow-hidden md:px-8">
          {children}
        </div>
        <RotatingLogo />
        <TailwindIndicator />
      </body>
    </html>
  );
}
